[package]
name = "doctavious-cli"
version = "0.1.0"
edition = "2018"
description = "Doctavious CLI"
repository = "https://github.com/doctavious/doctavious-cli"
keywords = ["cli", "documentation", "rfc", "adr"]
categories = ["documentation"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
clap = "2.33.3"
comfy-table = "1.1.1"
dirs = "2.0.2"
env_logger = "0.7"
git2 = "0.13.11"
lazy_static = "1.4"
log = "0.4"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
structopt = "0.3"
tempfile = "3.1.0"
toml = "0.5"
tokio = { version = "0.2", features = ["macros", "fs"] }
walkdir = "2.3.1"
which = "4.0.2"