[adr]
dir = "/var/folders/jm/1m24fjf96xv_458bclbpd1xh0000gn/T/.tmp9CM5at"
structure = "flat"
template_extension = "md"

[rfd]
dir = "docs/rfd"
structure = "flat"
template_extension = "md"

[til]
dir = "docs/til"
template_extension = "md"

# snippets

# scm


