[adr]
dir = "/var/folders/jm/1m24fjf96xv_458bclbpd1xh0000gn/T/.tmpK9JVDs"
structure = "flat"
template_extension = "md"

[rfd]
dir = "tests/resources/docs/rfd"
structure = "flat"
template_extension = "md"

[til]
dir = "./tests/resources/docs/til"
template_extension = "adoc"
